### ISSUE TITLE
关于EEG数据的疑问

### ISSUE THREAD

**Issue by danzhewuju** [HypoX64/candock#1]
你好：十分感谢你的项目，这的项目对我的研究有很大的帮助。
现在我有个疑问是关于EEG数据的。由于EEG数据受到其他脑电信号的干扰比较严重，因此我想知道你在进行训练时有没有经过滤波处理，如果有的的话能否给出对应的滤波频率？十分感谢！

**Comment by HypoX64** [comment]
感谢你提出的问题，在我的项目中直接使用了公开的数据集进行实验，并没有复杂的信号预处理过程。但目前我也在思考这个问题，一般来说用于睡眠分期的EEG信号的节律被的频率范围在0.5-30HZ,在项目组我并没有进行这个滤波步骤。在实际采集EEG信号时确实是会遇干扰较大的问题，我建议可以采用中值滤波以及0.2-35hz的带通滤波器进行处理后进行测试。
